# SPDX-FileCopyrightText: 2025 ChoreoAtlas contributors
# SPDX-License-Identifier: Apache-2.0
# GoReleaser配置 - ChoreoAtlas CLI CE版本发布
version: 2

project_name: choreoatlas

env:
  - CGO_ENABLED=0

builds:
  # 只构建CE版本
  - id: ce
    main: ./cmd/choreoatlas
    binary: choreoatlas
    ldflags:
      - -s -w
      - -X 'github.com/choreoatlas2025/cli/internal/cli.Version={{.Version}}'
      - -X 'github.com/choreoatlas2025/cli/internal/cli.GitCommit={{.ShortCommit}}'
      - -X 'github.com/choreoatlas2025/cli/internal/cli.BuildTime={{.Date}}'
      - -X 'github.com/choreoatlas2025/cli/internal/cli.BuildEdition=ce'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: ce-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - examples/**/*
      - docs/**/*
      - scripts/install.sh
      - scripts/install.ps1
    wrap_in_directory: false

checksum:
  name_template: 'SHA256SUMS.txt'

brews:
  - name: choreoatlas
    description: "Contract-as-Code CLI for mapping, validating, and guiding cross-service choreography"
    homepage: https://choreoatlas.io
    license: Apache-2.0
    repository:
      owner: choreoatlas2025
      name: homebrew-choreoatlas
      branch: main
    commit_author:
      name: ChoreoAtlas Bot
      email: bot@choreoatlas.io
    caveats: |
      This is the Community Edition (CE) build: zero telemetry, fully offline.
    install: |
      bin.install "choreoatlas"
      bin.install_symlink "choreoatlas" => "ca"
    test: |
      system "#{bin}/choreoatlas", "version"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Docker镜像
dockers:
  # GHCR (GitHub Container Registry) - 私有访问
  - image_templates:
      - "ghcr.io/choreoatlas2025/cli:{{ .Version }}-amd64"
      - "ghcr.io/choreoatlas2025/cli:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/choreoatlas2025/cli"
    extra_files:
      - examples
    ids:
      - ce

  - image_templates:
      - "ghcr.io/choreoatlas2025/cli:{{ .Version }}-arm64"
      - "ghcr.io/choreoatlas2025/cli:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/choreoatlas2025/cli"
    extra_files:
      - examples
    ids:
      - ce

  # Docker Hub - 公开访问
  - image_templates:
      - "choreoatlas/cli:{{ .Version }}-amd64"
      - "choreoatlas/cli:latest-amd64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/choreoatlas2025/cli"
    extra_files:
      - examples
    ids:
      - ce

  - image_templates:
      - "choreoatlas/cli:{{ .Version }}-arm64"
      - "choreoatlas/cli:latest-arm64"
    dockerfile: Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/choreoatlas2025/cli"
    extra_files:
      - examples
    ids:
      - ce

docker_manifests:
  # GHCR manifests
  - name_template: "ghcr.io/choreoatlas2025/cli:{{ .Version }}"
    image_templates:
      - "ghcr.io/choreoatlas2025/cli:{{ .Version }}-amd64"
      - "ghcr.io/choreoatlas2025/cli:{{ .Version }}-arm64"
  - name_template: "ghcr.io/choreoatlas2025/cli:latest"
    image_templates:
      - "ghcr.io/choreoatlas2025/cli:latest-amd64"
      - "ghcr.io/choreoatlas2025/cli:latest-arm64"
  
  # Docker Hub manifests (公开访问)
  - name_template: "choreoatlas/cli:{{ .Version }}"
    image_templates:
      - "choreoatlas/cli:{{ .Version }}-amd64"
      - "choreoatlas/cli:{{ .Version }}-arm64"
  - name_template: "choreoatlas/cli:latest"
    image_templates:
      - "choreoatlas/cli:latest-amd64"
      - "choreoatlas/cli:latest-arm64"

# SBOM生成（暂时禁用，因为syft工具未安装）
# sboms:
#   - artifacts: archive
#     documents:
#       - "{{ .ProjectName }}-{{ .Version }}-sbom.spdx.json"

# 发布设置
release:
  github:
    owner: choreoatlas2025
    name: cli
  draft: false
  prerelease: auto
  name_template: "ChoreoAtlas CLI {{ .Version }}"
  header: |
    ## ChoreoAtlas CLI {{ .Version }}
    
    从真实追踪中"映射-验证-引导"跨服务编排，用可执行契约治理交互逻辑。
    
    ### 快速开始
    ```bash
    # Homebrew
    brew install choreoatlas2025/homebrew-choreoatlas/choreoatlas
    
    # Shell / PowerShell installer (macOS/Linux/Windows)
    ./scripts/install.sh        # 或 scripts/install.ps1
    
    # Docker / GHCR
    docker run --rm choreoatlas/cli:{{ .Version }} version
    docker run --rm ghcr.io/choreoatlas2025/cli:{{ .Version }} version
    ```
    
    ### 10分钟体验
    ```bash
    choreoatlas --help
    # 查看examples/目录了解FlowSpec和ServiceSpec契约
    ```
  footer: |
    **Full Changelog**: https://github.com/choreoatlas2025/cli/compare/{{ .PreviousTag }}...{{ .Tag }}
    
    ---
    
    🚀 **Quick Start**: https://choreoatlas.io/quickstart  
    💬 **Community**: https://github.com/choreoatlas2025/cli/discussions  
    📚 **Docs**: https://choreoatlas.io
    
    **ChoreoAtlas CLI Community Edition** - Apache 2.0 开源许可
