// SPDX-FileCopyrightText: 2025 ChoreoAtlas contributors
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"flag"
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/choreoatlas2025/cli/internal/spec"
	"github.com/choreoatlas2025/cli/internal/trace"
)

func runDiscover(args []string) {
	fs := flag.NewFlagSet("discover", flag.ExitOnError)
	tracePath := fs.String("trace", "", "trace.json file path")
	out := fs.String("out", "discovered.flowspec.yaml", "FlowSpec output path")
	outServices := fs.String("out-services", "./services", "ServiceSpec output directory")
	title := fs.String("title", "Flow generated from trace", "FlowSpec title")
	noValidate := fs.Bool("no-validate", false, "Skip schema + lint validation gate (not recommended)")
	_ = fs.Parse(args)

	if *tracePath == "" {
		exitErr(fmt.Errorf("--trace parameter is required"))
	}

	tr, err := trace.LoadFromFile(*tracePath)
	if err != nil {
		exitErr(err)
	}

	// 按时间排序 spans
	sort.Slice(tr.Spans, func(i, j int) bool {
		return tr.Spans[i].StartNanos < tr.Spans[j].StartNanos
	})

	if err := discoverAndPersist(tr, *title, *out, *outServices, *noValidate); err != nil {
		exitErr(err)
	}
	fmt.Printf("Generated FlowSpec: %s\n", *out)

	fmt.Println("Dual contract generation complete! Please adjust the generated specifications as needed.")
}

// generateFlowYAML 从 trace 生成 FlowSpec YAML
func generateFlowYAML(tr *trace.Trace, title string, outServices string) string {
	var sb strings.Builder

	// Info 部分
	sb.WriteString("info:\n")
	fmt.Fprintf(&sb, "  title: %q\n\n", title)

	// Services 部分
	services := make(map[string]struct{})
	for _, span := range tr.Spans {
		if span.Service != "" {
			services[span.Service] = struct{}{}
		}
	}

	sb.WriteString("services:\n")
	names := make([]string, 0, len(services))
	for service := range services {
		names = append(names, service)
	}
	sort.Strings(names)
	for _, service := range names {
		fmt.Fprintf(&sb, "  %q:\n", service)
		fmt.Fprintf(&sb, "    spec: %q\n", filepath.ToSlash(filepath.Join(outServices, spec.ServiceSpecFilename(service))))
	}
	sb.WriteString("\n")

	// Flow 部分
	sb.WriteString("flow:\n")
	for i, span := range tr.Spans {
		stepName := fmt.Sprintf("Step%d-%s", i+1, span.Name)
		if span.Service == "" || span.Name == "" {
			continue // 跳过无效的 span
		}

		// 使用规范化的 operationId
		opId := spec.ComputeOperationID(span)
		fmt.Fprintf(&sb, "  - step: %q\n", stepName)
		fmt.Fprintf(&sb, "    call: %q\n", span.Service+"."+opId)

		// 不再将遥测属性塞入 FlowSpec.input，保持输入干净。
		// 如需传入真实调用实参（path/query/headers/body），请由用户后续补充。

		// Generate output (assuming each step has a response)
		outputVar := fmt.Sprintf("%sResponse", strings.ToLower(span.Service))
		sb.WriteString("    output:\n")
		fmt.Fprintf(&sb, "      %q: \"response.body\"  # TODO: Adjust output mapping\n", outputVar)

		sb.WriteString("\n")
	}

	// Add explanatory comments
	sb.WriteString("# This file was auto-generated by flowspec discover\n")
	sb.WriteString("# TODO list:\n")
	sb.WriteString("# 1. Create corresponding ServiceSpec files\n")
	sb.WriteString("# 2. Adjust input/output mappings and variable references\n")
	sb.WriteString("# 3. Verify step order and call relationships\n")
	sb.WriteString("# 4. Add appropriate meta information\n")

	return sb.String()
}
